server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-points
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-points
    username:
    password:

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-points-test
    username:
    password:
